#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sun May 31 16:38:21 CEST 2026
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=BSL_v10.0.zip
